<a href="https://colab.research.google.com/github/Anou26/Python-Programs/blob/master/CIS563_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTING IMPORTANT LIBRARIES
import pandas as pd
import numpy as np 
import math

In [ ]:
# IMPORTING DATASET 
from google.colab import drive
drive.mount("/content/drive")
data = pd.read_csv('/content/drive/My Drive/dataset.csv')

Mounted at /content/drive

In [ ]:
data.head()

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,obs_id,Month,Day,Year,...,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059258900,1,24,2021,...,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259256,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,OBS1059259639,1,24,2021,...,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001338,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,OBS1017001339,11,23,2020,...,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4

In [ ]:
data.describe()
#all the columns which are not included are categorical

,latitude,longitude,Month,Day,Year,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast
count,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.897105e+06,2.892591e+06,2.642502e+06
mean,4.070439e+01,-8.708081e+01,5.135655e+00,1.612868e+01,2.020698e+03,3.716377e+00,9.929744e-01,3.085494e-03,9.116953e-01,7.858224e-01,8.924702e-01,7.734052e-01,1.781914e+00,2.096626e+00
std,4.610126e+00,1.604554e+01,4.367908e+00,8.583022e+00,4.591886e-01,8.484951e+00,8.352411e-02,5.546147e-02,2.837376e-01,4.102507e-01,3.097856e-01,4.186283e-01,1.922218e+00,4.572139e+00
min,-3.313755e+01,-1.652876e+02,1.000000e+00,1.000000e+00,2.020000e+03,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e-03,0.000000e+00
25%,3.837521e+01,-9.334695e+01,2.000000e+00,9.000000e+00,2.020000e+03,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,0.000000e+00
50%,4.113672e+01,-8.060746e+01,3.000000e+00,1.600000e+01,2.021000e+03,2.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,0.000000e+00
75%,4.331610e+01,-7.610979e+01,1.100000e+01,2.300000e+01,2.021000e+03,4.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.001000e+00,1.000000e-03
max,6.551989e+01,8.182617e+01,1.200000e+01,3.100000e+01,2.021000e+03,5.000000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,8.001000e+00,1.500100e+01

**PROBLEM 4 - (PROGRAMMING) - DATA PREPROCESSING**

**1. Remove redundant attributes (all the same values) and meaningless attributes (all values are different).**

In [ ]:
len(data['PROJ_PERIOD_ID'].unique())

1

In [ ]:
data.drop('PROJ_PERIOD_ID', axis=1, inplace=True)  #redundant attribute

In [ ]:
data.columns

Index(['loc_id', 'latitude', 'longitude', 'subnational1_code',
       'entry_technique', 'sub_id', 'obs_id', 'Month', 'Day', 'Year',
       'species_code', 'how_many', 'valid', 'reviewed', 'day1_am', 'day1_pm',
       'day2_am', 'day2_pm', 'effort_hrs_atleast', 'snow_dep_atleast',
       'Data_Entry_Method'],
      dtype='object')

In [ ]:
len(data['obs_id'].unique())

2897105

In [ ]:
data.drop('obs_id', axis=1, inplace=True) #meaningless attribute

**2. Combine ‘date’, ‘month’ and ‘year’ into a single attribute.**

In [ ]:
data['Date'] = data['Month'].astype(str) + '-' + data['Day'].astype(str) + '-' + data['Year'].astype(str)

In [ ]:
data['Date']

0           1-24-2021
1           1-24-2021
2           1-24-2021
3          11-23-2020
4          11-23-2020
              ...
2897100     2-10-2021
2897101     2-10-2021
2897102     2-10-2021
2897103     2-10-2021
2897104     2-10-2021
Name: Date, Length: 2897105, dtype: object

In [ ]:
data #You will notice that a single attribute "Date" exists at the end of the dataframe where Day, Month and Year have been concatenated.

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,Month,Day,Year,species_code,...,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,Date
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,1,24,2021,amtspa,...,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,1,24,2021,blujay,...,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,1,24,2021,bkcchi,...,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,11,23,2020,dowwoo,...,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,11,23,2020,whbnut,...,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2897100,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,2,10,2021,daejun,...,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897101,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,2,10,2021,amerob,...,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897102,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,2,10,2021,houfin,...,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897103,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,2,10,2021,norcar,...,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897104,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,2,10,2021,rebnut,...,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021

In [ ]:
data.drop(['Day','Month','Year'], axis=1, inplace=True) #Because these are unnecessary now that we have a single attribute combining all.

In [ ]:
data

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,species_code,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,Date
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,amtspa,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,blujay,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,bkcchi,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,dowwoo,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,whbnut,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2897100,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,daejun,3,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897101,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,amerob,1,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897102,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,houfin,11,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897103,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,norcar,5,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021
2897104,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,rebnut,2,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021

**3. Convert all categorical attributes to quoted numbers, e.g. 1 → ‘1’, 2 → ‘2’,. . .**

The categorical variables that we have are 'loc_id',  'subnational1_code', 'entry_technique', 'sub_id',  'obs_id', 'species_code', 'Data_Entry_Method'

In [ ]:
# Let's create a new dataframe so that our existing dataframe doesn't get disturbed with the newer updates. This is to facilitate the further problems with ease.
import csv
new_df=pd.read_csv('/content/drive/My Drive/dataset.csv')
new_df.update("'" + new_df[['loc_id','subnational1_code','entry_technique', 'sub_id', 'obs_id', 'species_code', 'Data_Entry_Method']].astype(str) + "'") #We use this function to update the attributes at hand.
print(new_df)

              loc_id   latitude   longitude subnational1_code  \
0        'L12782033'  44.574148  -78.205608           'CA-ON'
1        'L12782033'  44.574148  -78.205608           'CA-ON'
2        'L12782033'  44.574148  -78.205608           'CA-ON'
3        'L12755941'  54.136873 -108.687862           'CA-SK'
4        'L12755941'  54.136873 -108.687862           'CA-SK'
...              ...        ...         ...               ...
2897100   'L2404002'  42.494631  -76.574364           'US-NY'
2897101   'L2404002'  42.494631  -76.574364           'US-NY'
2897102   'L2404002'  42.494631  -76.574364           'US-NY'
2897103   'L2404002'  42.494631  -76.574364           'US-NY'
2897104   'L2404002'  42.494631  -76.574364           'US-NY'

               entry_technique       sub_id           obs_id  Month  Day  \
0        '/GOOGLE_MAP/ZOOM:15'  'S79876486'  'OBS1059258900'      1   24
1        '/GOOGLE_MAP/ZOOM:15'  'S79876486'  'OBS1059259256'      1   24
2        '/GOOGLE_MAP/ZOOM:15'  'S79876486'  'OBS1059259639'      1   24
3        '/GOOGLE_MAP/ZOOM:17'  'S76634904'  'OBS1017001338'     11   23
4        '/GOOGLE_MAP/ZOOM:17'  'S76634904'  'OBS1017001339'     11   23
...                        ...          ...              ...    ...  ...
2897100  '/GOOGLE_MAP/ZOOM:15'  'S82225821'  'OBS1143975652'      2   10
2897101  '/GOOGLE_MAP/ZOOM:15'  'S82225821'  'OBS1143975653'      2   10
2897102  '/GOOGLE_MAP/ZOOM:15'  'S82225821'  'OBS1143975654'      2   10
2897103  '/GOOGLE_MAP/ZOOM:15'  'S82225821'  'OBS1143975655'      2   10
2897104  '/GOOGLE_MAP/ZOOM:15'  'S82225821'  'OBS1143975656'      2   10

         Year  ... how_many valid  reviewed  day1_am  day1_pm  day2_am  \
0        2021  ...        1     1         0        0        1        0
1        2021  ...        2     1         0        0        1        0
2        2021  ...        2     1         0        0        1        0
3        2020  ...        2     1         0        0        1        0
4        2020  ...        2     1         0        0        1        0
...       ...  ...      ...   ...       ...      ...      ...      ...
2897100  2021  ...        3     1         0        0        0        1
2897101  2021  ...        1     1         0        0        0        1
2897102  2021  ...       11     1         0        0        0        1
2897103  2021  ...        5     1         0        0        0        1
2897104  2021  ...        2     1         0        0        0        1

         day2_pm  effort_hrs_atleast  snow_dep_atleast  \
0              1               0.001             5.000
1              1               0.001             5.000
2              1               0.001             5.000
3              1               0.001            15.001
4              1               0.001            15.001
...          ...                 ...               ...
2897100        0               0.001             0.001
2897101        0               0.001             0.001
2897102        0               0.001             0.001
2897103        0               0.001             0.001
2897104        0               0.001             0.001

                Data_Entry_Method
0        'PFW Mobile App v1.1.17'
1        'PFW Mobile App v1.1.17'
2        'PFW Mobile App v1.1.17'
3                 'PFW Web 4.1.4'
4                 'PFW Web 4.1.4'
...                           ...
2897100           'PFW Web 4.1.4'
2897101           'PFW Web 4.1.4'
2897102           'PFW Web 4.1.4'
2897103           'PFW Web 4.1.4'
2897104           'PFW Web 4.1.4'

[2897105 rows x 22 columns]

**4. Discretize attribute ‘how many’ into bins of size 10, e.g. 0-10, 11-20,. . .**

In [94]:
x = data['how_many']

In [95]:
def create_bins(lower_bound, width, quantity):   # This is a function to create multiple bins, since the no. of the bins required is high.
  bins2 = []
  for low in range(lower_bound, 
                  lower_bound + quantity*width + 1, width):
      bins2.append((low, low+width))
  return bins2

In [92]:
bins2 = create_bins(lower_bound=0,            # Here, we're defining the start, interval_size (width) and the number of the bins(quantity).
                   width=10,
                   quantity=500)
bins3 = pd.IntervalIndex.from_tuples(bins2)   # Here, we're creating an index of intervals that are made of tuples closed on the same side.
x = data['how_many']
data['binned']=pd.cut(x,bins3)

In [93]:
data

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,species_code,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,Date,binned
0,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,amtspa,1,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021,"(0, 10]"
1,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,blujay,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021,"(0, 10]"
2,L12782033,44.574148,-78.205608,CA-ON,/GOOGLE_MAP/ZOOM:15,S79876486,bkcchi,2,1,0,0,1,0,1,0.001,5.000,PFW Mobile App v1.1.17,1-24-2021,"(0, 10]"
3,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,dowwoo,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020,"(0, 10]"
4,L12755941,54.136873,-108.687862,CA-SK,/GOOGLE_MAP/ZOOM:17,S76634904,whbnut,2,1,0,0,1,0,1,0.001,15.001,PFW Web 4.1.4,11-23-2020,"(0, 10]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2897100,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,daejun,3,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021,"(0, 10]"
2897101,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,amerob,1,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021,"(0, 10]"
2897102,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,houfin,11,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021,"(10, 20]"
2897103,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,norcar,5,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021,"(0, 10]"
2897104,L2404002,42.494631,-76.574364,US-NY,/GOOGLE_MAP/ZOOM:15,S82225821,rebnut,2,1,0,0,0,1,0,0.001,0.001,PFW Web 4.1.4,2-10-2021,"(0, 10]"

In [ ]:
max(data['how_many']) #Here, we're validating our binning method by testing it with a random row within the dataframe.
col = "how_many"
max_how_many = data.loc[data[col].idxmax()]
print(max_how_many)

loc_id                          L10154057
latitude                        43.954549
longitude                       -98.07045
subnational1_code                   US-SD
entry_technique       /GOOGLE_MAP/ZOOM:18
sub_id                          S76265134
species_code                       rewbla
how_many                             5000
valid                                   1
reviewed                                1
day1_am                                 1
day1_pm                                 1
day2_am                                 0
day2_pm                                 0
effort_hrs_atleast                  8.001
snow_dep_atleast                    0.001
Data_Entry_Method           PFW Web 4.0.4
Date                           11-14-2020
binned                       (4990, 5000]
Name: 661336, dtype: object

**5. Randomly sample 100 instances without replacement and save them as a single .csv file,
including attribute names.**

In [ ]:
sampled_data = data.sample(n=100,replace=False)

In [ ]:
sampled_data

,loc_id,latitude,longitude,subnational1_code,entry_technique,sub_id,species_code,how_many,valid,reviewed,day1_am,day1_pm,day2_am,day2_pm,effort_hrs_atleast,snow_dep_atleast,Data_Entry_Method,Date
2297445,L10132396,38.339754,-93.484070,US-MO,/GOOGLE_MAP/ZOOM:15,S76321858,whtspa,5,1,0,1,1,1,1,1.001,0.000,PFW Mobile App v1.1.14,11-14-2020
676395,L811462,38.930325,-77.254913,US-VA,ESRI_WEBSERVICE_STREET,S77505498,moudov,5,1,0,1,0,1,1,4.001,5.000,PFW Mobile App v1.1.17,12-15-2020
849985,L1025381,30.093443,-97.485718,US-TX,ESRI_WEBSERVICE_STREET,S76617234,carchi,2,1,0,1,1,1,1,1.001,0.000,PFW Web 4.1.4,11-22-2020
2851928,L39968,40.496296,-75.259441,US-PA,POSTCODE LAT/LONG LOOKUP,S79847674,bkcchi,3,1,0,1,1,1,1,4.001,0.000,PFW Web 4.1.4,12-5-2020
925687,L12672275,36.444056,-94.282580,US-AR,/GOOGLE_MAP/ZOOM:15,S76347074,rebwoo,2,1,0,1,1,1,1,1.001,0.000,PFW Web 4.0.4,11-15-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324781,L2410583,43.951295,-77.369902,CA-ON,/GOOGLE_MAP/ZOOM:15,S79561568,houspa,3,1,0,1,1,1,1,1.001,0.000,PFW Web 4.1.4,1-16-2021
2815812,L13086336,42.744846,-83.078122,US-MI,/GOOGLE_MAP/ZOOM:17,S81572431,tuftit,2,1,0,1,1,0,0,4.001,15.001,PFW Web 4.1.4,2-15-2021
1738250,L4152905,42.971936,-70.917049,US-NH,/GOOGLE_MAP/ZOOM:15,S79686014,easblu,3,1,0,1,1,1,1,1.001,0.000,PFW Web 4.1.4,1-21-2021
1551823,L10488576,41.833404,-72.299192,US-CT,/GOOGLE_MAP/ZOOM:15,S78482328,amegfi,1,1,0,1,1,1,0,8.001,0.000,PFW Web 4.1.4,12-28-2020
2642595,L12772384,40.245372,-79.285438,US-PA,/GOOGLE_MAP/ZOOM:15,S77347536,daejun,1,1,0,1,1,1,1,4.001,0.000,PFW Web 4.1.4,12-10-2020

In [ ]:
import os  
os.makedirs('C:/Assignment/sampled_data.csv', exist_ok=True)   #We're creating a new directory where the .csv file created just now will be stored.
sampled_data.to_csv('C:/Assignment/sampled_data.csv/out.csv')